# Generated by Django 2.0.3 on 2018-05-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_cd', models.IntegerField()),
                ('assigned_sockets', models.IntegerField(default=0)),
                ('level', models.BooleanField()),
                ('special', models.BooleanField()),
                ('socket', models.BooleanField()),
                ('cotton', models.BooleanField()),
                ('limit_break', models.BooleanField()),
                ('limit_abilities', models.BooleanField()),
                ('max_status', models.CharField(choices=[('0', ''), ('1', 'Maxed'), ('2', 'Bi-maxed'), ('3', 'Tri-maxed'), ('4', 'Quad-maxed'), ('5', 'Penta-maxed'), ('6', 'Rainbow-maxed')], max_length=13)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Box')),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='max_status',
        ),
        migrations.AddField(
            model_name='characterlog',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Character'),
        ),
    ]
