# Generated by Django 2.0.3 on 2018-05-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20180529_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='status',
        ),
        migrations.AddField(
            model_name='characterlog',
            name='status',
            field=models.CharField(choices=[('0', ''), ('1', 'Maxed'), ('2', 'Bi-maxed'), ('3', 'Tri-maxed'), ('4', 'Quad-maxed'), ('5', 'Penta-maxed'), ('6', 'Rainbow-maxed')], default=0, max_length=13),
            preserve_default=False,
        ),
    ]
