# Generated by Django 2.0.3 on 2018-05-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_characterlog_current_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterlog',
            name='max_status',
            field=models.CharField(choices=[('0', 'Base condition'), ('1', 'Maxed'), ('2', 'Bi-maxed'), ('3', 'Tri-maxed'), ('4', 'Quad-maxed'), ('5', 'Penta-maxed'), ('6', 'Rainbow-maxed')], max_length=13),
        ),
        migrations.AlterField(
            model_name='characterlog',
            name='status',
            field=models.CharField(choices=[('0', 'Base condition'), ('1', 'Maxed'), ('2', 'Bi-maxed'), ('3', 'Tri-maxed'), ('4', 'Quad-maxed'), ('5', 'Penta-maxed'), ('6', 'Rainbow-maxed')], max_length=13),
        ),
    ]
