# Generated by Django 2.0.3 on 2018-05-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20180529_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterlog',
            old_name='socket',
            new_name='sockets',
        ),
    ]
