# Generated by Django 2.0.3 on 2018-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20180529_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('RR', 'Rare Recruite'), ('S', 'Story'), ('C', 'Colosseum')], default='FN', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characterlog',
            name='max_status',
            field=models.CharField(choices=[('0', 'Nothing maxed'), ('1', 'Maxed'), ('2', 'Bi-maxed'), ('3', 'Tri-maxed'), ('4', 'Quad-maxed'), ('5', 'Penta-maxed'), ('6', 'Rainbow-maxed')], max_length=13),
        ),
        migrations.AlterField(
            model_name='characterlog',
            name='status',
            field=models.CharField(choices=[('0', 'Nothing maxed'), ('1', 'Maxed'), ('2', 'Bi-maxed'), ('3', 'Tri-maxed'), ('4', 'Quad-maxed'), ('5', 'Penta-maxed'), ('6', 'Rainbow-maxed')], max_length=13),
        ),
    ]
