# Generated by Django 2.0.3 on 2018-05-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20180530_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='island',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
