# Generated by Django 2.0.3 on 2018-05-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20180530_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterlog',
            name='farmed_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='island',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='island',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
