# Generated by Django 2.0.3 on 2018-05-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20180531_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterlog',
            name='owned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('RR', 'Rare Recruit'), ('S', 'Story'), ('C', 'Colosseum')], max_length=15),
        ),
        migrations.AlterField(
            model_name='island',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('RR', 'Rare Recruit'), ('S', 'Story'), ('C', 'Colosseum')], max_length=15),
        ),
    ]
