# Generated by Django 2.0.3 on 2018-05-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20180531_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.TextField(max_length=70),
        ),
    ]
