# Generated by Django 2.0.3 on 2018-05-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_auto_20180531_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.TextField(choices=[('STR', 'STR'), ('DEX', 'DEX'), ('QCK', 'QCK'), ('PSY', 'PSY'), ('INT', 'INT')], default='STR'),
            preserve_default=False,
        ),
    ]
