# Generated by Django 2.0.3 on 2018-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20180531_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='stars',
            field=models.CharField(choices=[('1', '★'), ('2', '★★'), ('3', '★★★'), ('4', '★★★★'), ('5', '★★★★★'), ('5+', '★★★★★+'), ('6', '★★★★★★'), ('6+', '★★★★★★+')], max_length=2),
        ),
    ]
