# Generated by Django 2.0.3 on 2018-06-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_auto_20180531_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('RR', 'Rare Recruit'), ('S', 'Story'), ('C', 'Colosseum'), ('SP', 'Special'), ('TM', 'Treasure Map')], max_length=15),
        ),
        migrations.AlterField(
            model_name='island',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('RR', 'Rare Recruit'), ('S', 'Story'), ('C', 'Colosseum'), ('SP', 'Special'), ('TM', 'Treasure Map')], max_length=15),
        ),
    ]
