# Generated by Django 2.0.3 on 2018-06-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_auto_20180604_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterlog',
            name='cc_atk',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterlog',
            name='cc_hp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterlog',
            name='cc_rcv',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
