# Generated by Django 2.0.6 on 2018-06-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_auto_20180605_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='island',
            name='active',
        ),
    ]
