# Generated by Django 2.0.6 on 2018-06-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_remove_island_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='family',
            field=models.CharField(default=' ', max_length=70),
            preserve_default=False,
        ),
    ]
