# Generated by Django 2.0.6 on 2018-06-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_character_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colosseum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('d1_start_time', models.DateTimeField()),
                ('d1_end_time', models.DateTimeField()),
                ('d2_start_time', models.DateTimeField()),
                ('d2_end_time', models.DateTimeField()),
                ('d3_start_time', models.DateTimeField()),
                ('d3_end_time', models.DateTimeField()),
                ('d4_start_time', models.DateTimeField()),
                ('d4_end_time', models.DateTimeField()),
                ('d5_start_time', models.DateTimeField(null=True)),
                ('d5_end_time', models.DateTimeField(null=True)),
                ('d6_start_time', models.DateTimeField(null=True)),
                ('d6_end_time', models.DateTimeField(null=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Character')),
            ],
        ),
        migrations.AlterField(
            model_name='characterlog',
            name='cc_atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterlog',
            name='cc_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='characterlog',
            name='cc_rcv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drop',
            name='special',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('SP', 'Special'), ('TM', 'Treasure Map')], max_length=15),
        ),
    ]
