# Generated by Django 2.0.6 on 2018-06-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20180607_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='colosseum',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='colosseum',
            name='name',
        ),
        migrations.AddField(
            model_name='colosseum',
            name='difficulty',
            field=models.CharField(choices=[('C', 'Chaos'), ('U', 'Underground'), ('E', 'Exhibition')], default='C', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colosseum',
            name='type',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Returning')], default='N', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colodrop',
            name='colo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Colosseum'),
        ),
        migrations.AddField(
            model_name='colodrop',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Character'),
        ),
    ]
