# Generated by Django 2.0.6 on 2018-06-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_auto_20180607_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colosseum',
            name='d5_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colosseum',
            name='d5_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colosseum',
            name='d6_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colosseum',
            name='d6_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
