# Generated by Django 2.0.6 on 2018-06-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_auto_20180607_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colodrop',
            name='colo',
        ),
        migrations.RemoveField(
            model_name='colodrop',
            name='drop',
        ),
        migrations.AlterField(
            model_name='island',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('SP', 'Special'), ('TM', 'Treasure Map'), ('C', 'Colosseum')], max_length=15),
        ),
        migrations.DeleteModel(
            name='ColoDrop',
        ),
        migrations.DeleteModel(
            name='Colosseum',
        ),
    ]
