# Generated by Django 2.0.6 on 2018-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_auto_20180607_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('SP', 'Special'), ('TM', 'Treasure Map'), ('C', 'Colosseum'), ('SK', 'Skill'), ('SS', 'Success')], max_length=15),
        ),
    ]
