# Generated by Django 2.0.6 on 2018-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0028_auto_20180612_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='family2',
            field=models.CharField(default='None', max_length=70),
        ),
    ]
