# Generated by Django 2.0.6 on 2018-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0029_character_family2'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='type2',
            field=models.TextField(choices=[('STR', 'STR'), ('DEX', 'DEX'), ('QCK', 'QCK'), ('PSY', 'PSY'), ('INT', 'INT'), ('None', '')], default='None'),
        ),
        migrations.AlterField(
            model_name='character',
            name='type',
            field=models.TextField(choices=[('STR', 'STR'), ('DEX', 'DEX'), ('QCK', 'QCK'), ('PSY', 'PSY'), ('INT', 'INT'), ('None', '')]),
        ),
    ]
