# Generated by Django 2.0.6 on 2018-06-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0030_auto_20180612_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='end_timeJ',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='island',
            name='start_timeJ',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='end_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='start_time',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
