# Generated by Django 2.0.6 on 2018-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0031_auto_20180612_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='japan',
            field=models.BooleanField(default=False),
        ),
    ]
