# Generated by Django 2.0.6 on 2018-06-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0031_auto_20180612_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='end_timeJ',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='start_timeJ',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
