# Generated by Django 2.0.6 on 2018-06-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0032_auto_20180612_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='end_time',
            field=models.DateTimeField(blank=True, default='2010-01-01 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='end_timeJ',
            field=models.DateTimeField(blank=True, default='2010-01-01 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='start_time',
            field=models.DateTimeField(blank=True, default='2010-01-01 00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='start_timeJ',
            field=models.DateTimeField(blank=True, default='2010-01-01 00:00:00', null=True),
        ),
    ]
