# Generated by Django 2.0.6 on 2018-06-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0032_box_japan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='kind',
            field=models.CharField(choices=[('R', 'Raid'), ('FN', 'Fortnight'), ('SP', 'Special'), ('TM', 'Treasure Map'), ('C', 'Colosseum'), ('SK', 'Skill'), ('SS', 'Success'), ('SKJ', 'SkillJAP'), ('SSJ', 'SuccessJAP')], max_length=15),
        ),
    ]
