# Generated by Django 2.0.6 on 2018-06-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0034_auto_20180612_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='island',
            name='end_timeJ',
            field=models.DateTimeField(default='2010-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='island',
            name='start_time',
            field=models.DateTimeField(default='2010-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='island',
            name='start_timeJ',
            field=models.DateTimeField(default='2010-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
